[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name    kafka
    Brokers kafka-1:9092,kafka-2:9092,kafka-3:9092
    Topics  siem.logs.raw.v1,logs.payments-api.v1
    Group_Id fb-siem
    Format   json
    Poll_MS  100
    rdkafka.security.protocol PLAINTEXT
    rdkafka.broker.address.family v4
    rdkafka.api.version.request.timeout.ms 30000

[OUTPUT]
    Name                 opensearch
    Match                *
    Host                 opensearch
    Port                 9200
    HTTP_User            # not needed since security is disabled
    HTTP_Passwd          # (empty)
    Logstash_Format      On
    Logstash_Prefix      logs
    Logstash_DateFormat  %Y.%m.%d
    Replace_Dots         On
    Suppress_Type_Name   On
    Workers              1