<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EBus" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Siem.Platform\Siem.Platform.Shared.Application.Abstractions\Siem.Platform.Shared.Application.Abstractions.csproj" />
    <ProjectReference Include="..\Siem.Platform.Logging.Application\Siem.Platform.Logging.Application.csproj" />
    <ProjectReference Include="..\Siem.Platform.Logging.Infrastructure\Siem.Platform.Logging.Infrastructure.csproj" />
  </ItemGroup>

</Project>
